import Link from "next/link";
import { ArrowRight, CalendarClock, CheckCircle2, Sparkles } from "lucide-react";
import PageHeader from "@/components/hub/PageHeader";
import { accountFor, followUpTasks, posts } from "@/components/hub/data";
import { DashboardStats } from "./DashboardStats";
import { RecentPosts } from "./RecentPosts";

export function HomeDashboard() {
  const nextPost = posts.find((post) => post.status === "Scheduled");
  return <><PageHeader eyebrow="Dashboard" title="From content to follow-up." description="Your functional overview of publishing, mock performance, classified conversations, and follow-up work." action={<Link href="/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#173b9a] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-900/15 hover:-translate-y-0.5 hover:bg-[#0f2e7d]">Create post <ArrowRight size={16} /></Link>} /><DashboardStats /><section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><RecentPosts /><div className="space-y-6"><article className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#153790] via-[#3155dc] to-[#637df7] p-6 text-white shadow-2xl shadow-blue-900/20"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><CalendarClock size={20} /></span><span className="rounded-full border border-white/25 bg-white/10 px-3 py-1 text-[0.65rem] font-bold uppercase tracking-[0.13em]">Next up</span></div><p className="mt-8 text-xs font-semibold text-blue-100">{nextPost ? accountFor(nextPost)?.platform : "No account"}</p><p className="mt-2 text-lg font-semibold leading-7">{nextPost?.content ?? "No scheduled post"}</p><p className="mt-5 text-xs text-blue-100">{nextPost?.scheduledAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(nextPost.scheduledAt)) : "Add a schedule"}</p></article><article className="glass-card rounded-3xl p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#dff9ee] text-emerald-700"><Sparkles size={18} /></span><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Lead-to-task</p><h2 className="text-lg font-semibold">Workflow health</h2></div></div><div className="mt-5 flex items-center justify-between rounded-2xl bg-white/70 p-4"><div><p className="text-2xl font-semibold">{followUpTasks.length}</p><p className="text-xs text-slate-500">Follow-up tasks</p></div><CheckCircle2 className="text-emerald-500" size={26} /></div></article></div></section></>;
}

